name = "hono-cloudflare-workers-example"
main = "src/index.ts"
compatibility_date = "2024-12-27"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "hono-prisma-d1"
database_id = "fed1c863-f0f3-4bfa-9705-4a16b929c8ef"
migrations_dir = "prisma/migrations"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1